export const SELECT_DEFFENSE_OPTION = 'SELECT_DEFFENSE_OPTION';
export const SELECT_ATTACK_OPTION = 'SELECT_ATTACK_OPTION';
export const INSERT_FIGHT_MESSAGE = 'INSERT_FIGHT_MESSAGE';
export const CLEAR_FIGHT_MESSAGES = 'CLEAR_FIGHT_MESSAGES';
export const RESET_FIGHT = 'RESET_FIGHT';
export const SET_USER_HEALTH = 'SET_USER_HEALTH';
export const SET_OPPONENT_HEALTH = 'SET_OPPONENT_HEALTH';

